### ISSUE TITLE
Track of possible improvements in the install script

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2092]
* As hls needs to be built from source to workaround many issues and there are users who want to use it that way, we are considering add a install from source method in ghcup (like the existing one for ghc):
  * https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/201
* We should:
  * [ ]  Revise the existing issues about the script to determine i f any should be fixed to help in that integration: https://github.com/haskell/haskell-language-server/issues?q=is%3Aopen+is%3Aissue+label%3A%22component%3A+install%22
  * [ ] Consider reopen and complete the pr about drop shake from the script to make it more lightweight: https://github.com/haskell/haskell-language-server/pull/63
  * [ ] Redesign error handling and messages to make it suitable for the ghcup usage (without lossing generality if possible)
    * https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/201#note_369276

//cc @hasufell @fendor

**Comment by hasufell** [comment]
Here are a few things:

1. The build system should be stable (whether it's directly buildable via cabal or we use a wrapper script/makefile/shell script doesn't matter, as long as it's guaranteed to work for future versions). This isn't a hard requirement, but if it isn't met, any build system change may require a new full ghcup release.
2. We need to be able to control the install destination and be able to pass arbitrary cabal flags to the invocations for maximum user control if needed. Currently, HLS build system uses `cabal-install-parsers` to read the global config. I'm not sure that's the best way. The build also needs to be sandboxed, so it must be possible to set `--store-dir`. This may be possible by overriding `CABAL_DIR` and adjusting all the variables in the config, but it seems rather clunky.
3. `findInstalledGhcs` relies on `stack-<ghcver>.yaml` to decide which GHC version is supported, even for cabal. That means you currently cannot build `hls-8.10.6`, although that should be perfectly buildable. Users will especially want this compile feature to use HLS with newly released GHC versions. This needs to be supported.

**Comment by jneira** [comment]
Ok, so @hasufell gently added the feature of compiling hls from source in ghcup directly so the original motivation has lost senses.
Will keep it as general issue to track improvments in the install script

**Comment by jneira** [comment]
The install script is deprecated and ghcup implemented the compilation without it
