### ISSUE TITLE
September monthly release (1.4.0) with ghc-8.10.6 and 8.10.7 support

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2176]
* And this never stops, time to plan and exexute the new release
* We missed the August release cause the hackage release for 1.3.0 has been blocked until today.
* I hope this one will be smoother thanks to the new hackage workflow and the clean up of cabal.project done to unblock 1.3.0

**Comment by vaclavsvejcar** [comment]
Great work! Is there any estimated date when `1.4.0` could be out?

**Comment by jneira** [comment]
Hi, as long as #2182 is merged and the build script generates the binaries

**Comment by jneira** [comment]
I've just cut the prerelase to trigger the generation of binaries, as in previous releases we have to attach manually the binary for windows and 8.8.4, include it in the ghcup tarball and update sha256sums
Will update here the definitive release
https://github.com/haskell/haskell-language-server/releases/tag/1.4.0

**Comment by jneira** [comment]
* In parallel, [i've cut the 1.4.0-hackage branch and upload it to my rep](https://github.com/jneira/haskell-language-server/tree/1.4.0-hackage)o, to see how the hackage part is going. It is failing with a weird cabal error while finding a build plan (https://github.com/jneira/haskell-language-server/runs/3608032008?check_suite_focus=true):

```
cabal: Could not resolve dependencies:
[__0] trying: ghcide-1.4.2.0 (user goal)
[__1] trying: base-4.15.0.0/installed-4.15.0.0 (dependency of ghcide)
[__2] trying: hls-brittany-plugin-1.0.1.0 (user goal)
[__3] next goal: czipwith (dependency of hls-brittany-plugin)
[__3] rejecting: czipwith-1.0.1.3 (conflict:
base==4.15.0.0/installed-4.15.0.0, czipwith => base>=4.11 && <4.15)
[__3] skipping: czipwith-1.0.1.2, czipwith-1.0.1.1, czipwith-1.0.1.0,
czipwith-1.0.0.0 (has the same characteristics that caused the previous
version to fail: excludes 'base' version 4.15.0.0)
[__3] fail (backjumping, conflict set: base, czipwith, hls-brittany-plugin)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: ghcide, base, czipwith,
hls-brittany-plugin
Try running with --minimize-conflict-set to improve the error message.
```

The weird thing is it should be using ghc-8.8.4 which has installed base 4.13.0.0 :thinking:

**Comment by jneira** [comment]
I've just make public the 1.4.0.0 release: https://github.com/haskell/haskell-language-server/releases/tag/1.4.0

**Comment by jneira** [comment]
And the hackage release is in its way: https://github.com/haskell/haskell-language-server/actions/runs/1239148799

**Comment by jneira** [comment]
The package candidates has been published, only left make them definitive:

- [ ] hls-retrie-plugin-1.0.1.2
- [ ] shake-bench-0.1.0.2
- [ ] hls-pragmas-plugin-1.0.1.0
- [ ] hls-call-hierarchy-plugin-1.0.1.0
- [ ] hls-ormolu-plugin-1.0.1.0
- [ ] ghcide-1.4.2.0
- [ ] hls-class-plugin-1.0.1.0
- [ ] ls-plugin-api-1.2.0.1
- [ ] hls-explicit-imports-plugin-1.0.1.0
- [ ] hls-tactics-plugin-1.4.0.0
- [ ] haskell-language-server-1.4.0.0
- [ ] hls-brittany-plugin-1.0.1.0

**Comment by jneira** [comment]
And we are in hackage too: https://hackage.haskell.org/package/haskell-language-server-1.4.0.0

So i think we can close this 😄
