### ISSUE TITLE
January release 1.6.0.0

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2424]
The machine never stops! Time to plan the new release.

* will include two new brand plugins
* and the continuous work of @pepeiborra improving performance
* [x] it will remove support for ghc-8.10.5
* [x] it should include the artifacts from gitlab, hopefully in a automated way (see https://github.com/haskell/ghcup-metadata/pull/11 and #2420
* [x] as noted by @hasufell the version of the gh release should match the hackage one (so 1.6.0.0)

as always if anyone feels strong enough to drive the release or collaborate with, help will be very welcomed :smiley_cat: 

-----------------------------

### prerelease sanity checks

- [x] trigger manually the hackage workflow *without* uploading the packages: https://github.com/jneira/haskell-language-server/actions/runs/1751828521
- [X] trigger manually the build workflow : https://github.com/jneira/haskell-language-server/actions/runs/1753316308
- [x] create a prerelease tag `1.6.0-check-gitlab` and push it to the [project repo in gitlab](https://gitlab.haskell.org/haskell/haskell-language-server) to check the build is fine: https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/46483

### github release

- [x] generate the list of pull requests finished since the last release using the [haskell script](https://github.com/haskell/haskell-language-server/blob/master/GenChangelogs.hs) in the project root.
  Nix users should run command `gen-hls-changelogs` (a wrapper of the script) in nix-shell instead.
- [x] add that list to the actual [Changelog](https://github.com/haskell/haskell-language-server/blob/master/ChangeLog.md) with a description of the release.
- [x] bump up versions of changed packages. All are optional but [haskell-language-server itself](https://github.com/haskell/haskell-language-server/blob/master/haskell-language-server.cabal).
- [x] create the tag and make an initial prerelease to trigger the ci workflow (see details below)
- [x] contact ghcup team (#haskell-ghcup irc channel or via its [repo](https://github.com/haskell/ghcup-metadata)) to try to sync our release and its inclusion in ghcup
- [x] in the github release edit page, check the attached binaries and the release description (usually the changelog entry) and uncheck the prerelease box
- [ ] make public the release in the usual social channels (not required but useful to spread the word :slightly_smiling_face:):
  - [x] irc
  - [x] matrix
  - [x] twitter
  - [x] discord
  - [x] discourse
  - [x] reddit

### hackage release

- [x] bump up package versions following the [pvp specification](https://pvp.haskell.org/) if they are not already updated. You could use [policeman](https://github.com/kowainik/policeman) to help with this step.
- [x] create 1.6.0-hackage branch to trigger the hackage github workflow which will upload all changed packages to hackage as candidates
- [ ] check manually candidates in hackage
- [ ] publish them definitely

### ghcup release

- [x] push the release tag to the [haskell-language-server gitlab repo](https://gitlab.haskell.org/haskell/haskell-language-server) to trigger the build of ghcup specific artifacts
- [x] download specific artifacts only available in the gitlab build and compute their sha256sum
- [x] upload them to the github release and complete the SHA256SUMS file
- [x] change ghcup metadata to include the new release in https://github.com/haskell/ghcup-metadata
  -  example pull request [here](https://github.com/haskell/ghcup-metadata/pull/11)
  - pull request: https://github.com/haskell/ghcup-metadata/pull/19

**Comment by hasufell** [comment]
>  push the release tag to the haskell-language-server gitlab repo to trigger the build of ghcup specific artifacts 
> change ghcup metadata to include the new release in https://github.com/haskell/ghcup-metadata


Please do this before the release, otherwise ghcup will lack behind the release for several days again.

**Comment by pepeiborra** [comment]
Should we wait until all the pieces from #2357 have landed?

**Comment by Anton-Latukha** [comment]
Addressed the CI-side part of GHC-8.10.5 support removal in #2427

**Comment by jneira** [comment]
> Should we wait until all the pieces from #2357 have landed?

Yeah no problem, i want to have the plan earlier this time but we can wait until mid month (i would like to do it before xmas holidays)

**Comment by jneira** [comment]
> > push the release tag to the haskell-language-server gitlab repo to trigger the build of ghcup specific artifacts
> > change ghcup metadata to include the new release in https://github.com/haskell/ghcup-metadata
> 
> Please do this before the release, otherwise ghcup will lack behind the release for several days again.

sure, we can push both tags at same time and keep the gh as a prerelase as long as we consider (last one was about one day as a prerelase)

**Comment by jneira** [comment]
> Should we wait until all the pieces from #2357 have landed?

is there another pending pr related with?

**Comment by jneira** [comment]
Reopen to track final changes:
* tag created: https://github.com/haskell/haskell-language-server/tree/1.6.0.0
* hackage build: https://github.com/haskell/haskell-language-server/actions/runs/1760982301
* release build: https://github.com/haskell/haskell-language-server/actions/runs/1760987798

**Comment by jneira** [comment]
The release build has failed for ubuntu 8.10.7 with:

```
<command line>: libtinfo.so.6: cannot open shared object file: No such file or directory
cabal: Failed to build ghcide-1.6.0.0 (which is required by exe:hls-wrapper
from hls-1.6.0.0).
```

**Comment by hasufell** [comment]
> The release build has failed for ubuntu 8.10.7 with:
> 
> ```
> <command line>: libtinfo.so.6: cannot open shared object file: No such file or directory
> cabal: Failed to build ghcide-1.6.0.0 (which is required by exe:hls-wrapper
> from hls-1.6.0.0).
> ```
> 
> I've reran the workflow deleting the already uploaded artifacts of the prerelease (as the workflow tries to upload them all and fails if an artifact with the same name is already attached to the release):https://github.com/haskell/haskell-language-server/actions/runs/1760987798

Which ubuntu version? Is ghcup used for installation?

**Comment by jneira** [comment]
> Which ubuntu version? Is ghcup used for installation?

ubuntu-18.04 and using ghcup, yeah
i had seen that error before in a previous chack build and rerunning fixed it

**Comment by jneira** [comment]
* The hackage workflow did not upload candidates
* It seems the input default value is not set if the workflow is triggered automatically via a branch instead a manual build, so i've reverted the condition with ad00c705 and triggered a new build: https://github.com/haskell/haskell-language-server/actions/runs/1761352874

**Comment by jneira** [comment]
All artifacts from the github build uploaded succesfully, we have to wait to gitlab one

**Comment by jneira** [comment]
* The hackage workflow has uploaded all packages as candidates, they need be marked as definitive:

* [ ] hie-compat-0.2.1.1
* [ ] hls-graph-1.6.0.0
* [ ] shake-bench-0.1.0.3
* [ ] ghcide-1.6.0.0
* [ ] hls-test-utils-1.2.0.0
* [ ] hls-floskell-plugin-1.0.1.0
* [ ] hls-call-hierarchy-plugin-1.0.2.0
* [ ] hls-explicit-imports-plugin-1.0.2.0
* [ ] hls-ormolu-plugin-1.0.2.0
* [ ] hls-retrie-plugin-1.0.2.0
* [ ] hls-pragmas-plugin-1.0.2.0
* [ ] hls-qualify-imported-names-plugin-1.0.1.0:  needs update hackage uploaders (add @eddiemundo and some other hls maintainer)
* [ ] hls-alternate-number-format-plugin-1.0.1.0: needs update hackage uploaders (add @drsooch  and some other hls maintainer)
* [ ] hls-stylish-haskell-plugin-1.0.1.0
* [ ] hls-refine-imports-plugin-1.0.1.0
* [ ] hls-splice-plugin-1.0.1.0
* [ ] hls-haddock-comments-plugin-1.0.1.0
* [ ] hls-brittany-plugin-1.0.2.0
* [ ] hls-class-plugin-1.0.2.0
* [ ] hls-plugin-api-1.3.0.0
* [ ] hls-tactics-plugin-1.6.0.0
* [ ] ls-hlint-plugin-1.0.3.0
* [ ] hls-eval-plugin-1.2.1.0
* [ ] hls-module-name-plugin-1.0.1.0
* [ ] hls-selection-range-plugin-1.0.0.0: needs update hackage uploaders (add  @kokobd and some other hls maintainer)
* [ ] hls-fourmolu-plugin-1.0.2.0
* [ ] haskell-language-server-1.6.0.0

//cc @pepeiborra for hackage uploaders change, the hackage users for @kokobd, @eddiemundo and @drsooch would be needed, so please add them in a comment

**Comment by jneira** [comment]
* pr to add hls-1.6.0.0 to ghcup: https://github.com/haskell/ghcup-metadata/pull/19

**Comment by hasufell** [comment]
So... I don't understand why the alpine binaries are static when we know static binaries are busted and these can't be used for other linux distros either...

If you want to support alpine, you need to build dynamic binaries for it. GHC bindists are also dynamic for alpine.

**Comment by jneira** [comment]
* We did not get to publish specific binaries for alpine due a tar generation problem but afaik linux binaries are built the same way we did since the beginning. So they should work or be broken in the same way.

**Comment by jneira** [comment]
Made the release definitve! 🎆

**Comment by kokobd** [comment]
> the hackage users for @kokobd, @eddiemundo and @drsooch would be needed, so please add them in a comment

@jneira @pepeiborra My hackage username is also `kokobd`. Is this what we need now? (not quite familiar with the hackage workflow)

**Comment by jneira** [comment]
yeah, we will add you to the plugin hackage maintainers and you will be able to upload, revise and all sort of things

**Comment by eddiemundo** [comment]
Oh didn't realize you meant we needed hackage accounts. In that case my username there is also `eddiemundo`.

**Comment by jneira** [comment]
Ok, the hackage release is also done: https://hackage.haskell.org/package/haskell-language-server-1.6.0.0 and @eddiemundo, @kokobd and @drsooch are hackage maintainers of their respective plugins, thanks to @pepeiborra 
thanks all for helping in the release!
