### ISSUE TITLE
Please, support GHC 9.0.2

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#2541]
This report is a notification & tracking report for https://www.haskell.org/ghc/blog/20211225-ghc-9.0.2-released.html support

Released on `2021-12-25`:

Complete release notes: https://downloads.haskell.org/ghc/9.0.2/docs/html/users_guide/9.0.2-notes.html

---

To have a glance for HLS: quoting

<details><summary>GHC 9.0.2 summary release notes</summary>

</p>

GHC 9.0.2 adds first-class AArch64/Darwin support using the LLVM backend, as well as fixing a number of critical correctness bugs with the 9.0.1 release, along with numerous improvements to compiler performance and memory usage:
  * [ ] First-class support for Apple M1 hardware using GHC’s LLVM ARM backend.
  * [ ] Fix a number of incorrect rewrite rules for `fromInteger` ([GHC#19345](https://gitlab.haskell.org/ghc/ghc/-/issues/19345), [GHC#20066](https://gitlab.haskell.org/ghc/ghc/-/issues/20066)).
  * [ ] Fix a number of runtime system and GC bugs which typically manifested in crashes ([GHC#19417](https://gitlab.haskell.org/ghc/ghc/-/issues/19417), [GHC#19297](https://gitlab.haskell.org/ghc/ghc/-/issues/19297), [GHC#19645](https://gitlab.haskell.org/ghc/ghc/-/issues/19645), [GHC#19667](https://gitlab.haskell.org/ghc/ghc/-/issues/19667), [GHC#18033](https://gitlab.haskell.org/ghc/ghc/-/issues/18033), [GHC#20132](https://gitlab.haskell.org/ghc/ghc/-/issues/20132), [GHC#19715](https://gitlab.haskell.org/ghc/ghc/-/issues/19715), [GHC#20399](https://gitlab.haskell.org/ghc/ghc/-/issues/20399), [GHC#20414](https://gitlab.haskell.org/ghc/ghc/-/issues/20414), [GHC#20649](https://gitlab.haskell.org/ghc/ghc/-/issues/20649), [GHC#19147](https://gitlab.haskell.org/ghc/ghc/-/issues/19147), [GHC#20051](https://gitlab.haskell.org/ghc/ghc/-/issues/20051), [GHC#20093](https://gitlab.haskell.org/ghc/ghc/-/issues/20093))
  * [ ] Fixes for various compiler performance and memory usage issues ([GHC#20134](https://gitlab.haskell.org/ghc/ghc/-/issues/20134), [GHC#13586](https://gitlab.haskell.org/ghc/ghc/-/issues/13586), [GHC#20509](https://gitlab.haskell.org/ghc/ghc/-/issues/20509), [GHC#19668](https://gitlab.haskell.org/ghc/ghc/-/issues/19668), [GHC#19996](https://gitlab.haskell.org/ghc/ghc/-/issues/19996), [GHC#19471](https://gitlab.haskell.org/ghc/ghc/-/issues/19471))
  * [ ] Improvements and bug fixes for the code generator and optimiser ([GHC#18638](https://gitlab.haskell.org/ghc/ghc/-/issues/18638), [GHC#19581](https://gitlab.haskell.org/ghc/ghc/-/issues/19581), [GHC#19700](https://gitlab.haskell.org/ghc/ghc/-/issues/19700), [GHC#19996](https://gitlab.haskell.org/ghc/ghc/-/issues/19996), [GHC#19181](https://gitlab.haskell.org/ghc/ghc/-/issues/19181), [GHC#19822](https://gitlab.haskell.org/ghc/ghc/-/issues/19822))
  * [ ] Fixes for typechecker bugs ([GHC#19410](https://gitlab.haskell.org/ghc/ghc/-/issues/19410) , [GHC#19191](https://gitlab.haskell.org/ghc/ghc/-/issues/19191), [GHC#19522](https://gitlab.haskell.org/ghc/ghc/-/issues/19522), [GHC#19400](https://gitlab.haskell.org/ghc/ghc/-/issues/19400), [GHC#19849](https://gitlab.haskell.org/ghc/ghc/-/issues/19849))
  * [ ] Bug fixes for the frontend and parser ([GHC#19397](https://gitlab.haskell.org/ghc/ghc/-/issues/19397), [GHC#19838](https://gitlab.haskell.org/ghc/ghc/-/issues/19838), [GHC#19518](https://gitlab.haskell.org/ghc/ghc/-/issues/19518), [GHC#19777](https://gitlab.haskell.org/ghc/ghc/-/issues/19777), [GHC#20242](https://gitlab.haskell.org/ghc/ghc/-/issues/20242), [GHC#19786](https://gitlab.haskell.org/ghc/ghc/-/issues/19786))
  * [ ] Emit warnings if Unicode Bidirectional Formatting characters are found in the source, possibly misleading code reviewers ([GHC#20263](https://gitlab.haskell.org/ghc/ghc/-/issues/20263), vulnerability website).
  * [ ] Many packaging-related fixes, including versioned `ghc-pkg` executables ([GHC#20087](https://gitlab.haskell.org/ghc/ghc/-/issues/20087)), and actually distributing GHC versions linked against the `native` big integer backend ([GHC#18967](https://gitlab.haskell.org/ghc/ghc/-/issues/18967), [GHC#19953](https://gitlab.haskell.org/ghc/ghc/-/issues/19953)) on both Windows and Alpine Linux. Some previous releases were still linked against the `GMP` library due to a misconfiguration of the builders.
  * [ ] A significant refactoring of `process` fixing numerous bugs mostly on Apple platforms ([GHC#19994](https://gitlab.haskell.org/ghc/ghc/-/issues/19994), process refactoring).
 * [x] Bug fixes for the linker on Darwin platforms ([GHC#20004](https://gitlab.haskell.org/ghc/ghc/-/issues/20004), [GHC#19968](https://gitlab.haskell.org/ghc/ghc/-/issues/19968), [GHC#19950](https://gitlab.haskell.org/ghc/ghc/-/issues/19950)).

</details>

---

A number of things to date (*2022-01-07*) is still not done: https://gitlab.haskell.org/ghc/ghc/-/issues/19632#note_400751, for example, boot `ghc-*` package versions not released to Hackage.

**Comment by jneira** [comment]
Thanks for opening the issue about. To have 9.0.2 available in ci we would need support for 9.0.2 in ghcup/chocolatey.

**Comment by hasufell** [comment]
ghcup support done

**Comment by jneira** [comment]
I am working on this
