### ISSUE TITLE
Support for GHC-9.0

### ISSUE THREAD

**Issue by mouse07410** [haskell/haskell-language-server#297]
## State of support

* The core functionality of haskell-language-server is supported. 
* Only some plugins and formatters needs to be updated to make it work with ghc-9.0.1 so they are not included until then.
* So you should consider use other ghc version only if you are specially interested in those plugins o formatters 

## Has ghc-9.0 support
- [x] `ghcide`
- [x] `haskell-language-server`
- [x] `hls-haddock-comments-plugin`
- [x] `hls-hlint-plugin`
- [x] `hls-importlens-plugin`
- [x] `hls-pragmas-plugin`
- [x] `hls-retrie-plugin`
- [x] `hls-eval-plugin` #1997
- [x] `hls-module-name-plugin` - Actually builds just fine. Was accidentally disabled
- [x] `hls-class-plugin` - #2475
- [x] `hls-refine-imports-plugin` - All deps build
- [x] `hls-splice-plugin` - All deps build
- [x] `hls-tactic-plugin` 
  - Blocked upstream by ghc-source-gen (https://github.com/google/ghc-source-gen/issues/77 / https://github.com/google/ghc-source-gen/pull/84)
  - Disabled some tests in GHC9 because they expect Wingman to build. See #1873 and the `expectFailIfGhc9` function
  - Pull request in progress: #2202
  - Finally added with #2582, follow up of the previous one

### Formatters
- [x] `hls-floskell-plugin`
- [x] `hls-ormolu-plugin`  - Support added with https://github.com/tweag/ormolu/issues/688
- [x] `hls-brittany-plugin` - Blocked upstream by brittany:ghc-lib-parser (https://github.com/lspitzner/brittany/issues/352)
- [X] `hls-fourmolu-plugin` - #2254
- [x] `hls-stylish-haskell-plugin` blocked upstream by 
  - stylish-haskell:ghc-lib-parser (https://github.com/haskell/stylish-haskell/issues/378)
  - https://github.com/haskell/stylish-haskell/issues/387

### Build system and CI
- [x] `stack-9.0.1.yaml` - Disables not-yet-working plugins and fetches upstream patches
- [x] `cabal-ghc901.project` - Used for disabling the not yet working plugins and fetching upstream patches
- [x] `flake.nix` - Needs to fetch upstream patches and disable not-yet-working plugins (#1995)
- [x] `.circleci/config.yml`
- [x] `.github/workflows/test.yml` - Uses the custom cabal.project and disables tests for non-working plugins. Needs to be updated when more plugins gain ghc-9.0.1 support
- [x] `.github/workflows/build.yml` - The release script is not updated to make a ghc-9.0.1 release yet (PR #1940)
- [x] `mergify.io` We should probably make it manditory for PRs to successfully build/test on ghc-9.0.1 as well

### Dependencies which needs updates and hackage release
- [X] [blaze-textual](https://github.com/bos/blaze-textual): https://github.com/bos/blaze-textual/pull/14. Released in hackage.
- [X] [czipwith](https://github.com/lspitzner/czipwith): https://github.com/lspitzner/czipwith/pull/2. 
- [X] [th-extras](https://github.com/mokus0/th-extras): https://github.com/mokus0/th-extras/pull/8. Needs hackage release: https://github.com/mokus0/th-extras/issues/10
- [X] [hie-bios](https://github.com/mpickering/hie-bios): https://github.com/mpickering/hie-bios/pull/300 (needs hackage release)
- [x] [dependent-sum](https://github.com/obsidiansystems/dependent-sum): https://github.com/obsidiansystems/dependent-sum/pull/57. Needs hackage release, see https://github.com/obsidiansystems/dependent-sum/issues/65
- [x] [ghc-api-compat](https://github.com/hsyl20/ghc-api-compat): https://github.com/haskell/haskell-language-server/pull/2128
- [x] [operational (shake-bench dependency)](https://github.com/HeinrichApfelmus/operational): https://github.com/HeinrichApfelmus/operational/pull/26 (needs hackage release https://github.com/HeinrichApfelmus/operational/issues/29)
  - Support added with #2249 

### Dependencies needed to inlcude brittany in hackage for 9.0:
- [X] multistate: https://github.com/lspitzner/multistate/pull/8, finally added with https://github.com/lspitzner/multistate/pull/11
- [x] data-tree-print: https://github.com/lspitzner/data-tree-print/pull/3
- [x] butcher: https://github.com/lspitzner/butcher/pull/8

**Comment by jneira** [comment]
It still has not been released

**Comment by jneira** [comment]
The release candidate has been uploaded: https://www.haskell.org/ghc/blog/20201229-ghc-9.0.1-rc1-released.html
So we could start to add support for it :smile:

**Comment by poscat0x04** [comment]
Now that ghc 9.0.1 has been released, maybe we should bump up the priority?

**Comment by jneira** [comment]
Yeah, but i guess it will be a complex change, given we are totally tied to ghc

**Comment by konn** [comment]
As the module structure of the `ghc` package drastically changed in 9.0.1, it might make sense to provide some compatibility layer in `ghcide` or its dependency. I once tried `ghc-api-compat` with GHC 9.0.1-rc1 as a compact layer, but its Hackage version didn't compile at that time.

**Comment by jneira** [comment]
We have already a compat module in ghcide but it does not export everything we need and it is misused in some code regions (for example i did not use in hlint puglin until recently)
We can leverage it while we add support for the new ghc version.

https://github.com/haskell/haskell-language-server/blob/master/ghcide/src/Development/IDE/GHC/Compat.hs

**Comment by jneira** [comment]
I've started a branch to give a quick try to ghc-9.0.1. I am afraid that only trying to build `hls-plugin-api` our simpler subpackage with less dependencies i have needed several `allow-newer`:

```
packages: .

allow-newer:
  regex-tdfa:base,
  regex-base:base,
  lens:template-haskell,
  parallel:base,
  haskell-lsp:base,
  haskell-lsp-types:base,
  hashable:base,
  time-compat:base,
  these:base,
  assoc:base,
  deepseq:base,
  hslogger:base
```

With this in a `cabal.project` in `./hls-plugin-api` i still got:

```
cabal: Could not resolve dependencies:
[__0] trying: hls-plugin-api-0.7.0.0 (user goal)
[__1] trying: lens-4.19.2 (dependency of hls-plugin-api)
[__2] trying: lens:setup.base-4.15.0.0/installed-4.15.0.0 (dependency of lens)
[__3] next goal: lens:setup.Cabal (dependency of lens)
[__3] rejecting: lens:setup.Cabal-3.4.0.0/installed-3.4.0.0,
lens:setup.Cabal-3.4.0.0 (constraint from maximum version of Cabal used by
Setup.hs requires <3.4)
```

So the build type setup of lens is preventing the build. Not sure how to avoid it in the call site.

So we have to wait or patch upstream packages. If we would try to install ghcide or hls with plugins the list of pending packages will be interminable so let's start with this one.

**Comment by jneira** [comment]
As commented in [reddit](https://www.reddit.com/r/haskell/comments/ja07ux/cabalinstall3400rc4_and_cabal3400rc4_are_now/) cabal-3.4.0.0 is required to avoid `constraint from maximum version of Cabal used bySetup.hs requires <3.4`

**Comment by Bodigrim** [comment]
You can try `lens-5`, which switched to `build-type: Simple` and bumped several upper bounds.

**Comment by anka-213** [comment]
I've managed to get `hls-plugin-api` to compile by adding a bunch of `source-repository-package`s with references to the various (mostly unmerged) upstream patches for ghc-9.0.1 support in `cabal.project`. And by adding
```
allow-newer:
    *:*,
```
to the same file.

You can check out this branch: https://github.com/anka-213/haskell-language-server/tree/ghc-9.0.1-with-lsp-1.2

It combines https://github.com/haskell/haskell-language-server/pull/1635 with #1631 in addition to modifying `cabal.project`.

**Comment by jneira** [comment]
@anka-213 In case it could help, i had a WIP branch over hls here: https://github.com/jneira/haskell-language-server/tree/ghc-9.0.1
It has the (now outdated) list of the precise packages that needed allow-newer at the moment

**Comment by mouse07410** [comment]
@jneira is there a downside to allowing _all_the packages "_newer_"?

**Comment by anka-213** [comment]
I've managed to get `ghcide` to compile now, but it fails with the error:
```
Message:  ghcide: Couldn't find a target code interpreter. Try with -fexternal-interpreter
```
Does anyone know what that could be caused by?

**Comment by anka-213** [comment]
For some reason, changing this
```haskell
env <- runGhc (Just libDir) getSession
```
to this
```haskell
env <- runGhc (Just libDir) $ do df <- getSessionDynFlags; setSessionDynFlags df; getSession
```
worked. The function `initDynLinker` was sad that the interpreter was not set, which apparently is set as a side effect of calling `setSessionDynFlags`.

But it is still very far from functional and I get new difficult-to debug errors. :/

**Comment by anka-213** [comment]
I've gotten ghcide working now! Checkout this branch: https://github.com/anka-213/haskell-language-server/tree/ghc-9.0.1-with-lsp-1.2

**Comment by anka-213** [comment]
Should we update the status of this issue now that #1649 has been merged?

## Has ghc-9.0.1 support
- [x] `ghcide`
- [x] `haskell-language-server`
- [x] `hls-haddock-comments-plugin`
- [x] `hls-hlint-plugin`
- [x] `hls-importlens-plugin`
- [x] `hls-pragmas-plugin`
- [x] `hls-retrie-plugin`
- [ ] `hls-module-name-plugin` - Actually builds just fine. Was accidentally disabled
- [ ] `hls-eval-plugin` - Some WIP, but it doesn't build yet
- [ ] `hls-class-plugin` - All deps build
- [ ] `hls-refine-imports-plugin` - All deps build (needs ghc-api-compat)
- [ ] `hls-splice-plugin` - All deps build (needs ghc-api-compat)
- [ ] `hls-tactic-plugin` - Blocked upstream by ghc-source-gen

### Formatters
- [x] `hls-floskell-plugin`
- [ ] `hls-brittany-plugin` - Blocked upstream by brittany:ghc-lib-parser
- [ ] `hls-fourmolu-plugin` - Blocked upstream by fourmolu:ghc-lib-parser
- [ ] `hls-ormolu-plugin`   - Blocked upstream by ormolu:ghc-lib-parser
- [ ] `hls-stylish-haskell-plugin` - Blocked upstream by stylish-haskell:ghc-lib-parser

### Build system and CI
- [x] `stack-9.0.1.yaml` - Disables not-yet-working plugins and fetches upstream patches
- [x] `cabal-ghc901.project` - Used for disabling the not yet working plugins and fetching upstream patches
- [ ] `flake.nix` - Needs to fetch upstream patches and disable not-yet-working plugins
- [x] `.circleci/config.yml`
- [x] `.github/workflows/test.yml` - Uses the custom cabal.project and disables tests for non-working plugins. Needs to be updated when more plugins gain ghc-9.0.1 support 
- [ ] `.github/workflows/build.yml` - The release script is not updated to make a ghc-9.0.1 release yet

**Comment by Ailrun** [comment]
Now mergify rules are all dropped in favor of the GitHub branch protection rule, so only thing we need to update is the protection rule.

**Comment by berberman** [comment]
`flake.nix` now supports GHC 9.0.1 (https://github.com/haskell/haskell-language-server/pull/1995): one can use
* `nix build .#haskell-language-server-901` to create HLS binary (which I think is extremely useful)
* `nix develop .#haskell-language-server-901-dev` to enter the shell for developing HLS itself

And eval plugin now works as well (https://github.com/haskell/haskell-language-server/pull/1997).

**Comment by AriFordsham** [comment]
GHC 9 should be working experimentally at https://github.com/AriFordsham/ghc-source-gen/tree/ari-f-ghc-9 (https://github.com/google/ghc-source-gen/pull/84).

**Comment by AriFordsham** [comment]
> Re `ghc-code-gen`: GHC 9 should be working experimentally at https://github.com/AriFordsham/ghc-source-gen/tree/ari-f-ghc-9 ([google/ghc-source-gen#84](https://github.com/google/ghc-source-gen/pull/84)).

Now merged and waiting for Hackage release

**Comment by svenpanne** [comment]
I'm a bit confused: The item list for the formatters has a tick mark for floskell, but looking at `stack-9.0.1.yaml` seems to indicate that there are no supported formatters at all at the moment.

What's still wrong with ormolu? I've just compiled ormolu itself with a Stackage nightly (using GHC 9.0.1), and everything seems to be fine.

**Comment by jneira** [comment]
I am afraid that stack.yaml is not up to date with the cabal.project, and maybe both lacks the already available support for ormolu

**Comment by svenpanne** [comment]
Hmmm, this basically means that this issue is rather useless: It contains tick marks for things not yet done and misses tick marks for things which have already been done... 😞 Is there already a planned date for a 1.4.0 release? Otherwise I will try to compile the HEAD from source, when I find some time...

**Comment by svenpanne** [comment]
I compared `cabal-ghc901.project` and `stack-9.0.1.yaml`, and there seem to be more things missing in the latter which are already enabled in the former:

- `./plugins/hls-class-plugin`
- `./plugins/hls-floskell-plugin`
- `./plugins/hls-ormolu-plugin`
- ` ./plugins/hls-refine-imports-plugin`
- `./shake-bench`

**Comment by jneira** [comment]
>  It contains tick marks for things not yet done

hmm what are those things?

it has become a little bit obsolete, thanks to note it, will update it asap

**Comment by jneira** [comment]
> I compared `cabal-ghc901.project` and `stack-9.0.1.yaml`, and there seem to be more things missing in the latter which are already enabled in the former:
> 
> - `./plugins/hls-class-plugin`
> - `./plugins/hls-floskell-plugin`
> - `./plugins/hls-ormolu-plugin`
> - ` ./plugins/hls-refine-imports-plugin`
> - `./shake-bench`
> 

nice, thanks to check them, do you wish to open a pr to update stack.yaml?

**Comment by svenpanne** [comment]
To get things in a sane state again, any changes should best be done by someone with the rights to change the .project/.yaml _and_ the tick marks at the beginning of this ticket. I didn't even compare all tick marks, but e.g. floskell has a mark, while it's still commented out in the .yaml.

Somehow the whole process seems to be a bit too manual, keeping 3 places in sync never works in any project I've seen, even only 2 places are enough to get lots of inconsistencies.

**Comment by jneira** [comment]
Yeah, but we need both cabal.project and stack.yaml to have support for both build tools, they are the source of truth cause hls built with each one does not include the plugins if they are not enabled in each config file. floskell is enabled in the cabal.project

The issue is only informative. You can't edit the first one but can comment with the new version and some maintainer can use it to update the main one then. And a pr updating the stack.yaml would be a good start ☺️

**Comment by anka-213** [comment]
> I'm a bit confused: The item list for the formatters has a tick mark for floskell, but looking at `stack-9.0.1.yaml` seems to indicate that there are no supported formatters at all at the moment.

Oh, sorry, I forgot to add that to the `stack.yaml` in the initial release.

> 
> What's still wrong with ormolu? I've just compiled ormolu itself with a Stackage nightly (using GHC 9.0.1), and everything seems to be fine.

Nothing's wrong with ormolu. This issue and the `cabal.project` and `stack.yaml` files hasn't been updated since that issue was resolved, that's all.

**Comment by jneira** [comment]
* Updated description with the state of the support

**Comment by jneira** [comment]
Support for fourmolu with #2254

**Comment by mouse07410** [comment]
Should this issue be closed, as HLS 1.4.0 seems to support GHC-9.0.1?

**Comment by anka-213** [comment]
@mouse07410 There are still a few plugins that doesn’t support GHC-9.0.1 yet, as can be seen in the checklist.

**Comment by jneira** [comment]
`czipwith` and `th-extras` already has 9.0.1 support in hacake

**Comment by jneira** [comment]
> `czipwith` and `th-extras` already has 9.0.1 support in hackage

So hls in hackage can be installed in ghc-9.0.1

**Comment by Anton-Latukha** [comment]
`brittany` solved mentioned report & release `0.14` with `9.0.2` support got published: https://hackage.haskell.org/package/brittany-0.14.0.0/changelog

**Comment by re-xyr** [comment]
Seems `stylish-haskell-0.14.0.0` supports GHC 9.0 now. Any chance we're going to have it?

**Comment by pepeiborra** [comment]
> Seems `stylish-haskell-0.14.0.0` supports GHC 9.0 now. Any chance we're going to have it?

Unfortunately hlint requires ghc-lib-parser `==9.0` whereas stylish-haskell wants `==9.2`, so no way to build HLS with both.

**Comment by re-xyr** [comment]
> Unfortunately hlint requires ghc-lib-parser ==9.0 whereas stylish-haskell wants ==9.2, so no way to build HLS with both.

Yes, I noticed that shortly after and filed an issue for `stylish-haskell`: https://github.com/haskell/stylish-haskell/issues/391

**Comment by July541** [comment]
I think we have fully supported ghc-9.0.
