### ISSUE TITLE
ghc-9.4 track list

### ISSUE THREAD

**Issue by July541** [haskell/haskell-language-server#3190]
We won't stop at 9.2, let's work for 9.4!

## Unsupported plugins
- [ ] hls-brittany-plugin
- [ ] hls-code-ragne-plugin
- [ ] hls-class-plugin
- [ ] hls-eval-plugin
- [ ] hls-floskell-plugin
- [ ] hls-fourmolu-plugin
- [ ] hls-gadt-plugin
- [ ] hls-haddock-comments-plugin
- [ ] hls-hlint-plugin (https://github.com/ndmitchell/hlint/issues/1413)
- [ ] hls-stan-plugin (won't support, the author of `stan` dropped ghc9)
- [ ] hls-ormolu-plugin (https://github.com/tweag/ormolu/pull/885)
- [ ] hls-rename-plugin
- [ ] hls-refactor-plugin
- [ ] hls-splice-plugin
- [ ] hls-stylish-haskell-plugin
- [ ] hls-tactics-plugin

## Allow-newer items
- [ ] Chart-diagrams:lens
- [ ] Chart:lens
- [ ] co-log-core:base
- [ ] constraints-extras:base, template-haskell
- [ ] dependent-sum:some
- [ ] diagrams-contrib:base, lens
- [ ] diagrams-postscript:base, lens
- [ ] diagrams-svg:base, lens
- [ ] ekg-json:base
- [ ] ghc-paths:Cabal
- [ ] haddock-library:base
- [ ] monoid-extras:base
- [ ] monoid-subclasses:vector
- [ ] svg-builder:base
- [ ] uuid:time
- [ ] vector-space:base
- [ ] ekg-wai:time

**Comment by lf-** [comment]
https://github.com/haskell/haskell-language-server/issues/3190 the import quickfix seems broken on 9.4

**Comment by July541** [comment]
ghc-exactprint for ghc-9.4 released now!

https://hackage.haskell.org/package/ghc-exactprint

**Comment by re-xyr** [comment]
`brittany` is no longer in maintenance: https://github.com/lspitzner/brittany/pull/377

We may not want to keep the support for brittany for GHC versions >= 9.2.

**Comment by santiweight** [comment]
Relevant issue for Brittany: https://github.com/haskell/haskell-language-server/issues/3346

**Comment by July541** [comment]
Close as we have full support ghc-9.4.
